server:
  port: 8080

spring:
  application:
    name: api-gateway-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}