server:
  port: 18080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: jwt
  datasource:
    url: jdbc:h2:mem:local;MODE=MySQL;DATABASE_TO_LOWER=TRUE  #테스트 환경에서는 h2 사용
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true #실행되는 쿼리 로그를 정렬하여 표시

    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 16379
